services:
#  database:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      SA_PASSWORD: "ForzaFiume1998#"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "1433:1433"  # Expose SQL Server port
#    volumes:
#      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # For schema/data initialization
  smtp:
    image: rnwood/smtp4dev
    container_name: smtp4dev-rendalicce
    ports:
      - "3000:80"   # Web interface
      - "2525:25"   # SMTP port
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your .NET Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 5000
      ConnectionStrings__Database: ${ConnectionStrings_Database}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
#    depends_on:
#      - database
    ports:
      - "5000:5000"  # Expose your .NET backend